### PR TITLE
VL-2052 MYSQL tables collation issue

### PR DESCRIPTION
**Pull request by hiteshprajapati**
## Description

The default Collation setting for MySQL version - 8.0 is 'utf8mb4_0900_ai_ci' when you create schema with default collation.

In fineract, for few tables , the migration script has specified collation setting other than utf8mb4_0900_ai_ci.
As a result we have tables with different collation setting in velocity db which mysql version 8.0 . And this results few errors while joins. 
So changing remaining 51 tables collation setting to 'utf8mb4_0900_ai_ci'.

collation-by-type

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by MageziArthur — APPROVED** [review]

**Review by MageziArthur — CHANGES_REQUESTED** [review]
I dont know how scalable this is though, I'd suggest a high level confguration instead of a per table fix.

**Review by hagafrank — APPROVED** [review]

**Comment by hiteshprajapati** [comment]
> I dont know how scalable this is though, I'd suggest a high level confguration instead of a per table fix.

I agree @MageziArthur . I have tried to apply change at schema level which doesn't work. So I have to go this way.
`ALTER DATABASE fineract_default CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;`

**Review by nassan — CHANGES_REQUESTED** [review]
Please provide analysis in the ticket as to how this happened before merging this

**Comment by hiteshprajapati** [comment]
> Please provide analysis in the ticket as to how this happened before merging this

@nassan : The JIRA ticket is updated with detailed analysis https://velocitycareerlabs.atlassian.net/browse/VL-2052?focusedCommentId=14219

**Review by nassan — APPROVED** [review]

**Pull request merged**
