### PR TITLE
VL-2051 - Search transactions by date range, amount and description

### PR DESCRIPTION
**Pull request by hiteshprajapati**
https://velocitycareerlabs.atlassian.net/browse/VL-2051

## Description
Backend changes for Search transactions by date range, amount and description.

## Checklist

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ ] Write the commit message as per https://github.com/apache/fineract/#pull-requests

- [ ] Acknowledge that we will not review PRs that are not passing the build _("green")_ - it is your responsibility to get a proposed PR to pass the build, not primarily the project's maintainers.

- [ ] Create/update unit or integration tests for verifying the changes made.

- [ ] Follow coding conventions at https://cwiki.apache.org/confluence/display/FINERACT/Coding+Conventions.

- [ ] Add required Swagger annotation and update API documentation at fineract-provider/src/main/resources/static/api-docs/apiLive.htm with details of any API changes

- [ ] Submission is not a "code dump".  (Large changes can be made "in repository" via a branch.  Ask on the developer mailing list for guidance, if required.)

FYI our guidelines for code reviews are at https://cwiki.apache.org/confluence/display/FINERACT/Code+Review+Guide.

### CODE REVIEW

**Review by nassan — CHANGES_REQUESTED** [review]
code freeze

**Comment by hiteshprajapati** [comment]
> code freeze

@nassan : Please let me know once the code freeze window is open again.

**Comment by hiteshprajapati** [comment]
@nassan : is Code Freeze window over? Can you please review the changes and let us know your feedback

**Review by MageziArthur — APPROVED** [review]
Looks good to me

**Review by nassan — APPROVED** [review]

**Pull request merged**
